import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	container: {
	  flex: 1,
	  backgroundColor: '#FFF0F8',
	},
	header: {
	  paddingTop: 60,
	  paddingHorizontal: 24,
	  paddingBottom: 30,
	  backgroundColor: '#fdf2f8',
	},
	title: {
	  fontSize: 28,
	  fontWeight: '700',
	  color: '#1f2937',
	  marginBottom: 4,
	},
	subtitle: {
	  fontSize: 14,
	  fontWeight: '600',
	  color: '#ec4899',
	  textAlign: 'center',
	},
	calendarWrapper: {
	  backgroundColor: '#fff',
	  marginHorizontal: 16,
	  marginTop: 16,
	  borderRadius: 16,
	  padding: 12,
	  elevation: 2,
	  shadowColor: '#000',
	  shadowOffset: { width: 0, height: 1 },
	  shadowOpacity: 0.1,
	  shadowRadius: 2,
	},
	calendar: {
	  borderRadius: 12,
	},
	legend: {
	  margin: 24,
	  padding: 20,
	  backgroundColor: '#fff',
	  borderRadius: 16,
	  elevation: 2,
	  shadowColor: '#000',
	  shadowOffset: { width: 0, height: 1 },
	  shadowOpacity: 0.1,
	  shadowRadius: 2,
	},
	legendTitle: {
	  fontSize: 18,
	  fontFamily: 'Bold',
	  // fontWeight: '700',
	  color: '#1f2937',
	  marginBottom: 12,
	},
	legendItems: {
	  gap: 8,
	},
	legendItem: {
	  flexDirection: 'row',
	  alignItems: 'center',
	  gap: 12,
	},
	legendColor: {
	  width: 16,
	  height: 16,
	  borderRadius: 8,
	},
	legendText: {
	  fontSize: 14,
	  fontWeight: '600',
	  color: '#4b5563',
	},
	modalOverlay: {
	  flex: 1,
	  backgroundColor: 'rgba(0, 0, 0, 0.6)',
	  justifyContent: 'flex-end',
	},
	modalContent: {
	  backgroundColor: '#fff',
	  borderTopLeftRadius: 28,
	  borderTopRightRadius: 28,
	  paddingTop: 24,
	  paddingHorizontal: 20,
	  paddingBottom: 34,
	  maxHeight: '85%',
	},
	modalHeader: {
	  flexDirection: 'row',
	  justifyContent: 'space-between',
	  alignItems: 'flex-start',
	  marginBottom: 24,
	  paddingBottom: 16,
	  borderBottomWidth: 1,
	  borderBottomColor: '#f3f4f6',
	},
	modalTitle: {
	  fontSize: 20,
	  fontWeight: '700',
	  color: '#1f2937',
	  letterSpacing: -0.2,
	},
	modalSubtitle: {
	  fontSize: 14,
	  color: '#6b7280',
	  marginTop: 4,
	},
	modalCloseButton: {
	  width: 36,
	  height: 36,
	  borderRadius: 18,
	  backgroundColor: '#f9fafb',
	  alignItems: 'center',
	  justifyContent: 'center',
	},
	modalActionsSection: {
	  marginBottom: 24,
	},
	modalSectionTitle: {
	  fontSize: 15,
	  fontWeight: '700',
	  color: '#1f2937',
	  marginBottom: 12,
	},
	modalActionsGrid: {
	  flexDirection: 'row',
	  gap: 10,
	},
	modalActionCard: {
	  flex: 1,
	  alignItems: 'center',
	  padding: 16,
	  borderRadius: 16,
	  borderWidth: 1.5,
	},
	modalActionCardPrimary: {
	  backgroundColor: '#fce7f3',
	  borderColor: '#fbcfe8',
	},
	modalActionCardDanger: {
	  backgroundColor: '#fee2e2',
	  borderColor: '#fecaca',
	},
	modalActionIcon: {
	  width: 48,
	  height: 48,
	  borderRadius: 24,
	  alignItems: 'center',
	  justifyContent: 'center',
	  marginBottom: 8,
	},
	modalActionLabel: {
	  fontSize: 13,
	  fontWeight: '600',
	  color: '#1f2937',
	  textAlign: 'center',
	},
	modalNotesSection: {
	  marginBottom: 24,
	},
	modalNotesScroll: {
	  gap: 12,
	  paddingRight: 4,
	},
	modalNoteCard: {
	  width: 160,
	  backgroundColor: '#f0fdf4',
	  borderRadius: 14,
	  padding: 12,
	  borderWidth: 1,
	  borderColor: '#bbf7d0',
	  position: 'relative',
	},
	modalNoteIconBadge: {
	  marginBottom: 8,
	},
	modalNoteIcon: {
	  fontSize: 24,
	},
	modalNoteTitle: {
	  fontSize: 14,
	  fontWeight: '700',
	  color: '#1f2937',
	  marginBottom: 4,
	},
	modalNoteText: {
	  fontSize: 12,
	  color: '#4b5563',
	  lineHeight: 16,
	},
	modalNoteReminder: {
	  position: 'absolute',
	  top: 8,
	  right: 8,
	  width: 20,
	  height: 20,
	  borderRadius: 10,
	  backgroundColor: '#fef3c7',
	  alignItems: 'center',
	  justifyContent: 'center',
	},
	modalNoteReminderText: {
	  fontSize: 10,
	},
	modalSymptomsSection: {
	  marginBottom: 8,
	},
	modalSymptomsPreview: {
	  backgroundColor: '#f9fafb',
	  borderRadius: 14,
	  padding: 16,
	  gap: 12,
	  marginBottom: 12,
	},
	modalSymptomPreviewItem: {
	  flexDirection: 'row',
	  alignItems: 'center',
	  gap: 10,
	},
	modalSymptomEmoji: {
	  fontSize: 18,
	},
	modalSymptomPreviewBar: {
	  flex: 1,
	  height: 6,
	  backgroundColor: '#e5e7eb',
	  borderRadius: 3,
	  overflow: 'hidden',
	},
	modalSymptomPreviewFill: {
	  height: '100%',
	  borderRadius: 3,
	},
	modalSymptomValue: {
	  fontSize: 12,
	  fontWeight: '700',
	  color: '#6b7280',
	  width: 30,
	  textAlign: 'right',
	},
	modalEditSymptomsButton: {
	  alignItems: 'center',
	  justifyContent: 'center',
	  paddingVertical: 10,
	  borderRadius: 12,
	  backgroundColor: '#f9fafb',
	  borderWidth: 1,
	  borderColor: '#e5e7eb',
	},
	modalEditSymptomsText: {
	  fontSize: 13,
	  fontWeight: '600',
	  color: '#8b5cf6',
	},
	symptomCard: {
	  marginTop: 20,
	  padding: 16,
	  backgroundColor: '#fdf2f8',
	  borderRadius: 16,
	  borderWidth: 1,
	  borderColor: '#fce7f3',
	  gap: 16,
	},
	symptomHeader: {
	  flexDirection: 'row',
	  justifyContent: 'space-between',
	  alignItems: 'flex-start',
	},
	symptomTitle: {
	  fontSize: 18,
	  fontWeight: '700',
	  color: '#1f2937',
	},
	symptomSubtitle: {
	  fontSize: 13,
	  color: '#6b7280',
	  marginTop: 4,
	},
	symptomHelperLink: {
	  fontSize: 13,
	  color: '#8b5cf6',
	  fontWeight: '600',
	},
	symptomRow: {
	  gap: 12,
	},
	symptomRowHeader: {
	  flexDirection: 'row',
	  justifyContent: 'space-between',
	  alignItems: 'center',
	},
	symptomLabel: {
	  fontSize: 15,
	  fontWeight: '600',
	  color: '#4b5563',
	},
	symptomHelper: {
	  fontSize: 12,
	  color: '#9ca3af',
	},
	symptomSliderWrapper: {
	  alignItems: 'center',
	  gap: 8,
	},
	symptomSliderLabels: {
	  width: 240,
	  flexDirection: 'row',
	  justifyContent: 'space-between',
	  paddingHorizontal: 4,
	},
	symptomLabelText: {
	  fontSize: 12,
	  color: '#6b7280',
	  fontWeight: '600',
	},
	saveSymptomsButton: {
	  marginTop: 4,
	  flexDirection: 'row',
	  alignItems: 'center',
	  justifyContent: 'center',
	  gap: 8,
	  paddingVertical: 14,
	  borderRadius: 12,
	  backgroundColor: '#ec4899',
	},
	saveSymptomsText: {
	  fontSize: 15,
	  fontWeight: '700',
	  color: '#fff',
	},
	unmarkPeriodButton: {
	  backgroundColor: '#dc2626',
	},
	deleteOption: {
	  backgroundColor: '#fef2f2',
	  borderWidth: 1,
	  borderColor: '#fecaca',
	},
	deleteOptionText: {
	  color: '#dc2626',
	},
	quickNotesSection: {
	  marginTop: 24,
	  gap: 12,
	},
	quickNotesTitle: {
	  fontSize: 16,
	  fontWeight: '700',
	  color: '#1f2937',
	  marginBottom: 8,
	},
	quickNotesSectionMain: {
	  marginHorizontal: 20,
	  marginTop: 20,
	  padding: 20,
	  backgroundColor: '#fff',
	  borderRadius: 16,
	  elevation: 2,
	  shadowColor: '#000',
	  shadowOffset: { width: 0, height: 1 },
	  shadowOpacity: 0.1,
	  shadowRadius: 2,
	  gap: 12,
	},
	quickNotesTitleMain: {
	  fontSize: 18,
	  fontWeight: '700',
	  color: '#1f2937',
	  marginBottom: 12,
	},
	quickNoteCard: {
	  backgroundColor: '#f0fdf4',
	  borderRadius: 12,
	  padding: 16,
	  borderWidth: 1,
	  borderColor: '#bbf7d0',
	  marginBottom: 8,
	},
	quickNoteHeader: {
	  flexDirection: 'row',
	  alignItems: 'flex-start',
	  gap: 12,
	},
	quickNoteIcon: {
	  fontSize: 24,
	},
	quickNoteContent: {
	  flex: 1,
	},
	quickNoteTitle: {
	  fontSize: 15,
	  fontWeight: '600',
	  color: '#1f2937',
	  marginBottom: 4,
	},
	quickNoteText: {
	  fontSize: 13,
	  color: '#4b5563',
	  lineHeight: 18,
	},
	reminderBadge: {
	  width: 24,
	  height: 24,
	  borderRadius: 12,
	  backgroundColor: '#fef3c7',
	  alignItems: 'center',
	  justifyContent: 'center',
	},
	reminderBadgeText: {
	  fontSize: 12,
	},
  });